export type Blog = {
  slug: string;
  title: string;
  content: string;
};

export const blogs = [
  {
    slug: "ai-disclaimer",
    title: "AI Disclaimer",
    content: "These blogs were totally generated by ChatGPT.",
  },
  {
    slug: "tech-trends-2024",
    title: "Top Tech Trends to Watch in 2024",
    content:
      "In this post, we explore the top tech trends for 2024, including AI advancements, blockchain innovations, and the rise of quantum computing.",
  },
  {
    slug: "travel-diaries-japan",
    title: "Travel Diaries: Exploring Japan",
    content:
      "Join me on an unforgettable journey through Japan, where I explore the vibrant culture, delicious food, and breathtaking landscapes.",
  },
  {
    slug: "healthy-eating-tips",
    title: "10 Tips for Healthy Eating",
    content:
      "Discover practical tips for maintaining a healthy diet, including meal planning, understanding nutrition labels, and staying hydrated.",
  },
  {
    slug: "minimalist-lifestyle",
    title: "Embracing a Minimalist Lifestyle",
    content:
      "Learn how adopting a minimalist lifestyle can bring more clarity, reduce stress, and increase your overall happiness.",
  },
  {
    slug: "javascript-best-practices",
    title: "Best Practices for Writing Clean JavaScript",
    content:
      "Improve your JavaScript code by following these best practices, including code organization, naming conventions, and avoiding common pitfalls.",
  },
  {
    slug: "mindfulness-meditation",
    title: "The Power of Mindfulness and Meditation",
    content:
      "Explore the benefits of mindfulness and meditation, and learn simple techniques to incorporate them into your daily routine.",
  },
  {
    slug: "sustainable-living",
    title: "Sustainable Living: Tips for a Greener Future",
    content:
      "Find out how you can live a more sustainable lifestyle by reducing waste, conserving energy, and making eco-friendly choices.",
  },
  {
    slug: "remote-work-success",
    title: "How to Succeed at Remote Work",
    content:
      "Get tips on staying productive, maintaining work-life balance, and fostering communication while working remotely.",
  },
];
